using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectBA.Models.Entities;

namespace ProjectBA.Services
{
    public interface IBenhAnNoiKhoaServices
    {
        Task<dynamic> ThongTin();
        Task<dynamic> ThemThongTin([FromBody] Benhannoikhoa benhannoikhoa);
    }

    public class BenhAnNoiKhoaServices : IBenhAnNoiKhoaServices
    {
        private HospitalContext _context;

        public BenhAnNoiKhoaServices(HospitalContext context)
        {
            _context = context;
        }

        public async Task<dynamic> ThemThongTin([FromBody] Benhannoikhoa benhannoikhoa)
        {
            try
            {
                var data = await _context.Benhannoikhoas.AddAsync(benhannoikhoa);
                await _context.SaveChangesAsync();
                return new
                {
                    data = data
                };
            }
            catch (Exception ex)
            {
                return new
                {
                    message = ex.Message
                };
            }
        }

        //public async Task<dynamic> CapNhatThongTin([FromBody] Benhanngoaikhoa benhanngoaikhoa)
        //{
        //    try
        //    {
        //        Benhanngoaikhoa ba = await _context.Benhanngoaikhoas.FindAsync(benhanngoaikhoa.Mabenhan);
        //        ba.Macoquanchuquan = benhanngoaikhoa.Macoquanchuquan;

        //        _context.Benhanngoaikhoas.Update(ba);
        //        await _context.SaveChangesAsync();
        //        return new
        //        {
        //            data = ba
        //        };
        //    }
        //}

        public async Task<dynamic> ThongTin()
        {
            var data = await _context.Benhannoikhoas
                .Select(x => new
                {
                    Mabenhan = x.Mabenhan,
                    Macoquanchuquan = x.Macoquanchuquan,
                    Tencoquanchuquan = x.Tencoquanchuquan,
                    Macosokbcb = x.Macosokbcb,
                    Tencosokbcb = x.Tencosokbcb,
                    Hovaten = x.Hovaten,
                    Ngaysinh = x.Ngaysinh,
                    Tuoi = x.Tuoi,
                    Gioitinh = x.Gioitinh,
                    Dienthoai = x.Dienthoai,
                    Nghenghiep = x.Nghenghiep,
                    Dantoc = x.Dantoc,
                    Madantoc = x.Madantoc,
                    Quoctich = x.Quoctich,
                    Maquoctich = x.Maquoctich,
                    Sonha = x.Sonha,
                    Thonpho = x.Thonpho,
                    Xaphuong = x.Xaphuong,
                    Maxaphuong = x.Maxaphuong,
                    Huyen = x.Huyen,
                    Mahuyen = x.Mahuyen,
                    Thanhpho = x.Thanhpho,
                    Mathanhpho = x.Mathanhpho,
                    Doituong = x.Doituong,
                    Sothebhyt = x.Sothebhyt,
                    Cancuoc = x.Cancuoc,
                    Hotenthannhan = x.Hotenthannhan,
                    Dienthoaithannhan = x.Dienthoaithannhan,
                    Thoigianvaovien = x.Thoigianvaovien,
                    Tiepnhantu = x.Tiepnhantu,
                    Macosokbcbchuyenden = x.Macosokbcbchuyenden,
                    Noichuyenden = x.Noichuyenden,
                    Vaokhoa = x.Vaokhoa,
                    Thoigianvaokhoa = x.Thoigianvaokhoa,
                    Songayvaokhoa = x.Songayvaokhoa,
                    Chuyenkhoa = x.Chuyenkhoa,
                    Thoigianchuyenkhoa = x.Thoigianchuyenkhoa,
                    Songaychuyenkhoa = x.Songaychuyenkhoa,
                    Tongsongaydieutri = x.Tongsongaydieutri,
                    Macosokbcbchuyendi = x.Macosokbcbchuyendi,
                    Noichuyendi = x.Noichuyendi,
                    Thoigianravien = x.Thoigianravien,
                    Lydoravien = x.Lydoravien,
                    Machuandoanvaovien = x.Machuandoanvaovien,
                    Chuandoanvaovien = x.Chuandoanvaovien,
                    Mabenhchinh = x.Mabenhchinh,
                    Benhchinh = x.Benhchinh,
                    Mabenhkemtheo = x.Mabenhkemtheo,
                    Benhkemtheo = x.Benhkemtheo,
                    Mabienchung = x.Mabienchung,
                    Bienchung = x.Bienchung,
                    Ghichuravien = x.Ghichuravien,
                    Tinhtrangravien = x.Tinhtrangravien,
                    Thoigiantuvong = x.Thoigiantuvong,
                    Thoidiemtuvong = x.Thoidiemtuvong,
                    Manguyennhanchinhtuvong = x.Manguyennhanchinhtuvong,
                    Nguyennhanchinhtuvong = x.Nguyennhanchinhtuvong,
                    Thoigiandaidienky = x.Thoigiandaidienky,
                    Lanhdaokhoa = x.Lanhdaokhoa,
                    Daidiencosokbcb = x.Daidiencosokbcb,
                    Lydovaovien = x.Lydovaovien,
                    Tinhtrangvao = x.Tinhtrangvao,
                    Giothu = x.Giothu,
                    Ngaythu = x.Ngaythu,
                    Dienbienbenh = x.Dienbienbenh,
                    Chuandoanbenhvienkhac = x.Chuandoanbenhvienkhac,
                    Motachuandoanbenhvienkhac = x.Motachuandoanbenhvienkhac,
                    Diung = x.Diung,
                    Diungthuoc = x.Diungthuoc,
                    Diunghoachat = x.Diunghoachat,
                    Diungthucpham = x.Diungthucpham,
                    Diungkhac = x.Diungkhac,
                    Thuocdangdung = x.Thuocdangdung,
                    Tiensubenh = x.Tiensubenh,
                    Tiensubenhtimmach = x.Tiensubenhtimmach,
                    Tiensubenhhohap = x.Tiensubenhhohap,
                    Tiensubenhtieuhoa = x.Tiensubenhtieuhoa,
                    Tiensubenhnoitiet = x.Tiensubenhnoitiet,
                    Tiensubenhthankinh = x.Tiensubenhthankinh,
                    Tiensubenhthan = x.Tiensubenhthan,
                    Tiensubenhxuongkhop = x.Tiensubenhxuongkhop,
                    Tiensubenhungthu = x.Tiensubenhungthu,
                    Tiensubenhkhac = x.Tiensubenhkhac,
                    Tiensuphauthuat = x.Tiensuphauthuat,
                    Yeutonguyco = x.Yeutonguyco,
                    Yeutonguycothuocla = x.Yeutonguycothuocla,
                    Thoigiansudungthuocla = x.Thoigiansudungthuocla,
                    Lieuluongsudungthuocla = x.Lieuluongsudungthuocla,
                    Yeutonguycothuoclao = x.Yeutonguycothuoclao,
                    Thoigiansudungthuoclao = x.Thoigiansudungthuoclao,
                    Yeutonguycoruoubia = x.Yeutonguycoruoubia,
                    Lieuluongsudungruoubia = x.Lieuluongsudungruoubia,
                    Yeutonguycochatgaynghien = x.Yeutonguycochatgaynghien,
                    Loaichatgaynghien = x.Loaichatgaynghien,
                    Thoigiansudungchatgaynghien = x.Thoigiansudungchatgaynghien,
                    Yeutonguycotiepxuchoachat = x.Yeutonguycotiepxuchoachat,
                    Loaihoachat = x.Loaihoachat,
                    Thoigiantiepxuchoachat = x.Thoigiantiepxuchoachat,
                    Yeutonguycokhac = x.Yeutonguycokhac,
                    Tiensugiadinh = x.Tiensugiadinh,
                    Nguoimac = x.Nguoimac,
                    Tenbenh = x.Tenbenh,
                    Yeutodichte = x.Yeutodichte,
                    Dasongonoitruoctrongkhibenh = x.Dasongonoitruoctrongkhibenh,
                    Thoigiandasong = x.Thoigiandasong,
                    Benhcaptinhnoisinhsong = x.Benhcaptinhnoisinhsong,
                    Moisinh = x.Moisinh,
                    Toanthan = x.Toanthan,
                    Tiepxuctot = x.Tiepxuctot,
                    Nguga = x.Nguga,
                    Lomo = x.Lomo,
                    Honme = x.Honme,
                    Glasgow = x.Glasgow,
                    Daniemmac = x.Daniemmac,
                    Ketmacmat = x.Ketmacmat,
                    Luoi = x.Luoi,
                    Longtocmong = x.Longtocmong,
                    Tuyengiap = x.Tuyengiap,
                    Hachsoduoc = x.Hachsoduoc,
                    Vitrihach = x.Vitrihach,
                    Soluonghach = x.Soluonghach,
                    Duongkinhhach = x.Duongkinhhach,
                    Didong = x.Didong,
                    Dau = x.Dau,
                    Mach = x.Mach,
                    Nhietdo = x.Nhietdo,
                    Huyetap = x.Huyetap,
                    Nhiptho = x.Nhiptho,
                    Cannang = x.Cannang,
                    Chieucao = x.Chieucao,
                    Spo2 = x.Spo2,
                    Bmi = x.Bmi,
                    Xuathuyetduoida = x.Xuathuyetduoida,
                    Vitrixuathuyetduoida = x.Vitrixuathuyetduoida,
                    Xuathuyetniemmac = x.Xuathuyetniemmac,
                    Vitrixuathuyetniemmac = x.Vitrixuathuyetniemmac,
                    Phu = x.Phu,
                    Vitriphu = x.Vitriphu,
                    Tinhchat = x.Tinhchat,
                    Toanthanbenhkhac = x.Toanthanbenhkhac,
                    Tuanhoan = x.Tuanhoan,
                    Daunguc = x.Daunguc,
                    Tinhtrangdaunguc = x.Tinhtrangdaunguc,
                    Hoihopdanhtrongnguc = x.Hoihopdanhtrongnguc,
                    Nhipnhanh = x.Nhipnhanh,
                    Nhipcham = x.Nhipcham,
                    Loannhip = x.Loannhip,
                    Daplech = x.Daplech,
                    Diendaptim = x.Diendaptim,
                    Tiengtimmo = x.Tiengtimmo,
                    Vitritiengtimmo = x.Vitritiengtimmo,
                    Thoitamthu = x.Thoitamthu,
                    Vitrithoitamthu = x.Vitrithoitamthu,
                    Mucdothoitamthu = x.Mucdothoitamthu,
                    Dorungthoitamthu = x.Dorungthoitamthu,
                    Thoitamtruong = x.Thoitamtruong,
                    Vitrithoitamtruong = x.Vitrithoitamtruong,
                    Mucdothoitamtruong = x.Mucdothoitamtruong,
                    Dorungthoitamtruong = x.Dorungthoitamtruong,
                    Rungtamtruong = x.Rungtamtruong,
                    Vitrirungtamtruong = x.Vitrirungtamtruong,
                    Mucdorungtamtruong = x.Mucdorungtamtruong,
                    Thoilientuc = x.Thoilientuc,
                    Vitrithoilientuc = x.Vitrithoilientuc,
                    Tiengthoidongmach = x.Tiengthoidongmach,
                    Vitritiengthoidongmach = x.Vitritiengthoidongmach,
                    Tuanhoankhac = x.Tuanhoankhac,
                    Hohap = x.Hohap,
                    Khotho = x.Khotho,
                    Biendanglongnguc = x.Biendanglongnguc,
                    Goo = x.Goo,
                    Vitrigo = x.Vitrigo,
                    Riraophenang = x.Riraophenang,
                    Vitririraophenang = x.Vitririraophenang,
                    Rungthanh = x.Rungthanh,
                    Vitrirungthanh = x.Vitrirungthanh,
                    Rale = x.Rale,
                    Tinhtrangrale = x.Tinhtrangrale,
                    Hohapkhac = x.Hohapkhac,
                    Tieuhoa = x.Tieuhoa,
                    Daubung = x.Daubung,
                    Vitridaubung = x.Vitridaubung,
                    Buonnon = x.Buonnon,
                    Non = x.Non,
                    Tinhtrangmaunon = x.Tinhtrangmaunon,
                    Daitienphancomau = x.Daitienphancomau,
                    Tinhtrangdaitienphancomau = x.Tinhtrangdaitienphancomau,
                    Tieuchay = x.Tieuchay,
                    Solantieuchay = x.Solantieuchay,
                    Chuongbung = x.Chuongbung,
                    Phanungthanhbung = x.Phanungthanhbung,
                    Lach = x.Lach,
                    Vitrilach = x.Vitrilach,
                    Gan = x.Gan,
                    Vitrigan = x.Vitrigan,
                    Tieuhoakhac = x.Tieuhoakhac,
                    Than = x.Than,
                    Mausacnuoctieu = x.Mausacnuoctieu,
                    Mausac = x.Mausac,
                    Thetich = x.Thetich,
                    Tieubuot = x.Tieubuot,
                    Tieurat = x.Tieurat,
                    Caubangquang = x.Caubangquang,
                    Daudiemnieuquan = x.Daudiemnieuquan,
                    Vitridaudiemnieuquan = x.Vitridaudiemnieuquan,
                    Rungthan = x.Rungthan,
                    Thankhac = x.Thankhac,
                    Thankinh = x.Thankinh,
                    Cocung = x.Cocung,
                    Dauhieumangnao = x.Dauhieumangnao,
                    Coluc = x.Coluc,
                    Vitricoluc = x.Vitricoluc,
                    Truonglucco = x.Truonglucco,
                    Vitritruonglucco = x.Vitritruonglucco,
                    Phanxaganxuong = x.Phanxaganxuong,
                    Vitriphanxaganxuong = x.Vitriphanxaganxuong,
                    Lietmotphanhainguoiphai = x.Lietmotphanhainguoiphai,
                    Lietmotphanhainguoitrai = x.Lietmotphanhainguoitrai,
                    Liethaichiduoi = x.Liethaichiduoi,
                    Liettuchi = x.Liettuchi,
                    Thankinhkhac = x.Thankinhkhac,
                    Coxuongkhop = x.Coxuongkhop,
                    Dauco = x.Dauco,
                    Vitridauco = x.Vitridauco,
                    Daukhop = x.Daukhop,
                    Vitridaukhop = x.Vitridaukhop,
                    Sungdokhop = x.Sungdokhop,
                    Vitrisuongdokhop = x.Vitrisuongdokhop,
                    Daucotsong = x.Daucotsong,
                    Vitridaucotsong = x.Vitridaucotsong,
                    Hanchevandongkhop = x.Hanchevandongkhop,
                    Vitrihanchevandongkhop = x.Vitrihanchevandongkhop,
                    Hattphi = x.Hattphi,
                    Vitrihattophi = x.Vitrihattophi,
                    Daucungkhopbuoisang = x.Daucungkhopbuoisang,
                    Coxuongkhopkhac = x.Coxuongkhopkhac,
                    Taimuihong = x.Taimuihong,
                    Tai = x.Tai,
                    Motatai = x.Motatai,
                    Mui = x.Mui,
                    Motamui = x.Motamui,
                    Hong = x.Hong,
                    Motahong = x.Motahong,
                    Thanhquan = x.Thanhquan,
                    Motathanhquan = x.Motathanhquan,
                    Taimuihongkhac = x.Taimuihongkhac,
                    Ranghammat = x.Ranghammat,
                    Motaranghammat = x.Motaranghammat,
                    Ranghammatkhac = x.Ranghammatkhac,
                    Mat = x.Mat,
                    Motamat = x.Motamat,
                    Matkhac = x.Matkhac,
                    Noitiet = x.Noitiet,
                    Motanoitiet = x.Motanoitiet,
                    Anuong = x.Anuong,
                    Noitietdinhduongkhac = x.Noitietdinhduongkhac,
                    Benhlykhac = x.Benhlykhac,
                    Xetnghiemlamsang = x.Xetnghiemlamsang,
                    Motaxetnghiemlamsang = x.Motaxetnghiemlamsang,
                    Tomtatbenhan = x.Tomtatbenhan,
                    Chuandoanlucvaovienkdt = x.Chuandoanlucvaovienkdt,
                    Machuandoanlucvaovienkdt = x.Machuandoanlucvaovienkdt,
                    Chuandoanphanbiekdt = x.Chuandoanphanbiekdt,
                    Machuandoanphanbietkdt = x.Machuandoanphanbietkdt,
                    Benhchinhkdt = x.Benhchinhkdt,
                    Mabenhchinhkdt = x.Mabenhchinhkdt,
                    Benhkemtheokdt = x.Benhkemtheokdt,
                    Mabenhkemtheokdt = x.Mabenhkemtheokdt,
                    Bienchungkdt = x.Bienchungkdt,
                    Mabienchungkdt = x.Mabienchungkdt,
                    Tienluonggan = x.Tienluonggan,
                    Tienluongxa = x.Tienluongxa,
                    Huongdieutritt = x.Huongdieutritt,
                    Chedochamsoc = x.Chedochamsoc,
                    Chedodinhduong = x.Chedodinhduong,
                    Phuchoichucnang = x.Phuchoichucnang,
                    Motaphuchoichucnang = x.Motaphuchoichucnang,
                    Tuvansuckhoe = x.Tuvansuckhoe,
                    Motatuvansuckhoe = x.Motatuvansuckhoe,
                    Thoiganbacsilambenhanky = x.Thoiganbacsilambenhanky,
                    Bacsilambenhan = x.Bacsilambenhan,
                    Tomtatquatrinhbenhly = x.Tomtatquatrinhbenhly,
                    Dauhieulamsangchinh = x.Dauhieulamsangchinh,
                    Tomtatketquaxetnghiem = x.Tomtatketquaxetnghiem,
                    Noikhoa = x.Noikhoa,
                    Motanoikhoa = x.Motanoikhoa,
                    Phauthuatthuthuat = x.Phauthuatthuthuat,
                    Motaphauthuatthuthuat = x.Motaphauthuatthuthuat,
                    Tinhtrangravientk = x.Tinhtrangravientk,
                    Huongdieutri = x.Huongdieutri,
                    Thoigianbacsidieutriky = x.Thoigianbacsidieutriky,
                    Bacsidieutri = x.Bacsidieutri
                }).FirstOrDefaultAsync();
            return data;
        }
    }
}
