using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectBA.Models.Entities;

namespace ProjectBA.Services
{
    public interface IBenhAnNgoaiKhoaServices
    {
        Task<dynamic> ThongTin();
        Task<dynamic> ThemThongTin([FromBody] Benhanngoaikhoa benhanngoaikhoa);
    }

    public class BenhAnNgoaiKhoaServices : IBenhAnNgoaiKhoaServices
    {
        private HospitalContext _context;

        public BenhAnNgoaiKhoaServices(HospitalContext context)
        {
            _context = context;
        }
        
        public async Task <dynamic> ThemThongTin([FromBody] Benhanngoaikhoa benhanngoaikhoa)
        {
            try
            {
                var data = await _context.Benhanngoaikhoas.AddAsync(benhanngoaikhoa);
                await _context.SaveChangesAsync();
                return new
                {
                    data = data
                };
            }
            catch (Exception ex)
            {
                return new
                {
                    message = ex.Message
                };
            }
        }

        /*public async Task <dynamic> XoaThongTin()*/

        //public async Task<dynamic> CapNhatThongTin([FromBody] Benhanngoaikhoa benhanngoaikhoa)
        //{
        //    try
        //    {
        //        Benhanngoaikhoa ba = await _context.Benhanngoaikhoas.FindAsync(benhanngoaikhoa.Mabenhan);
        //        ba.Macoquanchuquan = benhanngoaikhoa.Macoquanchuquan;

        //        _context.Benhanngoaikhoas.Update(ba);
        //        await _context.SaveChangesAsync();
        //        return new
        //        {
        //            data = ba
        //        };
        //    }
        //}

        public async Task <dynamic> ThongTin()
        {
            var data = await _context.Benhanngoaikhoas
                .Select(x => new
                {
                    Mabenhan = x.Mabenhan,
                    Macoquanchuquan = x.Macoquanchuquan,
                    Tencoquanchuquan = x.Tencoquanchuquan,
                    Macosokbcb = x.Macosokbcb,
                    Tencosokbcb = x.Tencosokbcb,
                    Hovaten = x.Hovaten,
                    Ngaysinh = x.Ngaysinh,
                    Tuoi = x.Tuoi,
                    Gioitinh = x.Gioitinh,
                    Dienthoai = x.Dienthoai,
                    Nghenghiep = x.Nghenghiep,
                    Dantoc = x.Dantoc,
                    Madantoc = x.Madantoc,
                    Quoctich = x.Quoctich,
                    Maquoctich = x.Maquoctich,
                    Sonha = x.Sonha,
                    Thonpho = x.Thonpho,
                    Xaphuong = x.Xaphuong,
                    Maxaphuong = x.Maxaphuong,
                    Huyen = x.Huyen,
                    Mahuyen = x.Mahuyen,
                    Thanhpho = x.Thanhpho,
                    Mathanhpho = x.Mathanhpho,
                    Doituong = x.Doituong,
                    Sothebhyt = x.Sothebhyt,
                    Cancuoc = x.Cancuoc,
                    Hotenthannhan = x.Hotenthannhan,
                    Dienthoaithannhan = x.Dienthoaithannhan,
                    Thoigianvaovien = x.Thoigianvaovien,
                    Tiepnhantu = x.Tiepnhantu,
                    Macosokbcbchuyenden = x.Macosokbcbchuyenden,
                    Noichuyenden = x.Noichuyenden,
                    Vaokhoa = x.Vaokhoa,
                    Thoigianvaokhoa = x.Thoigianvaokhoa,
                    Songayvaokhoa = x.Songayvaokhoa,
                    Chuyenkhoa = x.Chuyenkhoa,
                    Thoigianchuyenkhoa = x.Thoigianchuyenkhoa,
                    Songaychuyenkhoa = x.Songaychuyenkhoa,
                    Tongsongaydieutri = x.Tongsongaydieutri,
                    Macosokbcbchuyendi = x.Macosokbcbchuyendi,
                    Noichuyendi = x.Noichuyendi,
                    Thoigianravien = x.Thoigianravien,
                    Lydoravien = x.Lydoravien,
                    Machuandoanvaovien = x.Machuandoanvaovien,
                    Chuandoanvaovien = x.Chuandoanvaovien,
                    Mabenhchinh = x.Mabenhchinh,
                    Benhchinh = x.Benhchinh,
                    Mabenhkemtheo = x.Mabenhkemtheo,
                    Benhkemtheo = x.Benhkemtheo,
                    Mabienchung = x.Mabienchung,
                    Bienchung = x.Bienchung,
                    Ghichuravien = x.Ghichuravien,
                    Tinhtrangravien = x.Tinhtrangravien,
                    Thoigiantuvong = x.Thoigiantuvong,
                    Thoidiemtuvong = x.Thoidiemtuvong,
                    Manguyennhanchinhtuvong = x.Manguyennhanchinhtuvong,
                    Nguyennhanchinhtuvong = x.Nguyennhanchinhtuvong,
                    Thoigiandaidienky = x.Thoigiandaidienky,
                    Lanhdaokhoa = x.Lanhdaokhoa,
                    Daidiencosokbcb = x.Daidiencosokbcb,
                    Lydovaovien = x.Lydovaovien,
                    Tinhtrangvao = x.Tinhtrangvao,
                    Giothu = x.Giothu,
                    Ngaythu = x.Ngaythu,
                    Dienbienbenh = x.Dienbienbenh,
                    Chuandoanbenhvienkhac = x.Chuandoanbenhvienkhac,
                    Motachuandoanbenhvienkhac = x.Motachuandoanbenhvienkhac,
                    Diung = x.Diung,
                    Diungthuoc = x.Diungthuoc,
                    Diunghoachat = x.Diunghoachat,
                    Diungthucpham = x.Diungthucpham,
                    Diungkhac = x.Diungkhac,
                    Thuocdangdung = x.Thuocdangdung,
                    Tiensubenh = x.Tiensubenh,
                    Tiensubenhtimmach = x.Tiensubenhtimmach,
                    Tiensubenhhohap = x.Tiensubenhhohap,
                    Tiensubenhtieuhoa = x.Tiensubenhtieuhoa,
                    Tiensubenhnoitiet = x.Tiensubenhnoitiet,
                    Tiensubenhthankinh = x.Tiensubenhthankinh,
                    Tiensubenhthan = x.Tiensubenhthan,
                    Tiensubenhxuongkhop = x.Tiensubenhxuongkhop,
                    Tiensubenhungthu = x.Tiensubenhungthu,
                    Tiensubenhkhac = x.Tiensubenhkhac,
                    Tiensuphauthuat = x.Tiensuphauthuat,
                    Motatsphauthuat1 = x.Motatsphauthuat1,
                    Motatsphauthuat2 = x.Motatsphauthuat2,
                    Motatsphauthuat3 = x.Motatsphauthuat3,
                    Yeutonguyco = x.Yeutonguyco,
                    Yeutonguycothuocla = x.Yeutonguycothuocla,
                    Thoigiansudungthuocla = x.Thoigiansudungthuocla,
                    Lieuluongsudungthuocla = x.Lieuluongsudungthuocla,
                    Yeutonguycothuoclao = x.Yeutonguycothuoclao,
                    Thoigiansudungthuoclao = x.Thoigiansudungthuoclao,
                    Yeutonguycoruoubia = x.Yeutonguycoruoubia,
                    Lieuluongsudungruoubia = x.Lieuluongsudungruoubia,
                    Yeutonguycochatgaynghien = x.Yeutonguycochatgaynghien,
                    Loaichatgaynghien = x.Loaichatgaynghien,
                    Thoigiansudungchatgaynghien = x.Thoigiansudungchatgaynghien,
                    Yeutonguycotiepxuchoachat = x.Yeutonguycotiepxuchoachat,
                    Loaihoachat = x.Loaihoachat,
                    Thoigiantiepxuchoachat = x.Thoigiantiepxuchoachat,
                    Yeutonguycokhac = x.Yeutonguycokhac,
                    Tiensugiadinh = x.Tiensugiadinh,
                    Benhtimmach = x.Benhtimmach,
                    Nguoimacbenhtimmach = x.Nguoimacbenhtimmach,
                    Tanghuyetap = x.Tanghuyetap,
                    Nguoimacbenhtanghuyetap = x.Nguoimacbenhtanghuyetap,
                    Tamthan = x.Tamthan,
                    Nguoimacbenhtamthan = x.Nguoimacbenhtamthan,
                    Benhgout = x.Benhgout,
                    Nguoimacbenhgout = x.Nguoimacbenhgout,
                    Benhhethong = x.Benhhethong,
                    Nguoimacbenhhethong = x.Nguoimacbenhhethong,
                    Ungthu = x.Ungthu,
                    Nguoimacbenhungthu = x.Nguoimacbenhungthu,
                    Lao = x.Lao,
                    Nguoimacbenhlao = x.Nguoimacbenhlao,
                    Hensuyen = x.Hensuyen,
                    Nguoimacbenhhensuyen = x.Nguoimacbenhhensuyen,
                    Daithaoduong = x.Daithaoduong,
                    Nguoimacbenhdaithaoduong = x.Nguoimacbenhdaithaoduong,
                    Benhdongkinh = x.Benhdongkinh,
                    Nguoimacbenhdongkinh = x.Nguoimacbenhdongkinh,
                    Benhlqdenchuyenhoa = x.Benhlqdenchuyenhoa,
                    Nguoimacbenhlqdenchuyenhoa = x.Nguoimacbenhlqdenchuyenhoa,
                    Benhkhac = x.Benhkhac,
                    Nguoimacbenhkhac = x.Nguoimacbenhkhac,
                    Toanthan = x.Toanthan,
                    Mach = x.Mach,
                    Nhietdo = x.Nhietdo,
                    Huyetap = x.Huyetap,
                    Nhiptho = x.Nhiptho,
                    Cannang = x.Cannang,
                    Chieucao = x.Chieucao,
                    Spo2 = x.Spo2,
                    Bmi = x.Bmi,
                    Tiepxuctot = x.Tiepxuctot,
                    Tiepxuccham = x.Tiepxuccham,
                    Nguga = x.Nguga,
                    Lomo = x.Lomo,
                    Honme = x.Honme,
                    Da = x.Da,
                    Niemmac = x.Niemmac,
                    Moikho = x.Moikho,
                    Tuyengiap = x.Tuyengiap,
                    Hachngoaivi = x.Hachngoaivi,
                    Phu = x.Phu,
                    Vitriphu = x.Vitriphu,
                    Xuathuyetduoida = x.Xuathuyetduoida,
                    Toanthankhac = x.Toanthankhac,
                    Tuanhoanvahohap = x.Tuanhoanvahohap,
                    Candoi = x.Candoi,
                    Corut = x.Corut,
                    Bamtim = x.Bamtim,
                    Hohapdaochieu = x.Hohapdaochieu,
                    Mangsuondidong = x.Mangsuondidong,
                    Thogangsuc = x.Thogangsuc,
                    Vetthuongthanhnguc = x.Vetthuongthanhnguc,
                    Motavtthanhnguc = x.Motavtthanhnguc,
                    Trankhiduoida = x.Trankhiduoida,
                    Rungmiu = x.Rungmiu,
                    Tiengtim = x.Tiengtim,
                    Tiengtimdeu = x.Tiengtimdeu,
                    Tiengtimbatthuong = x.Tiengtimbatthuong,
                    Riraophenang = x.Riraophenang,
                    Motariraophenang = x.Motariraophenang,
                    Rale = x.Rale,
                    Motarale = x.Motarale,
                    Tuanhoanvahohapkhac = x.Tuanhoanvahohapkhac,
                    Tieuhoa = x.Tieuhoa,
                    Bungchuong = x.Bungchuong,
                    Seomocu = x.Seomocu,
                    Vtktseomocu = x.Vtktseomocu,
                    Tuanhoanbanghe = x.Tuanhoanbanghe,
                    Quairuotnoi = x.Quairuotnoi,
                    Dauhieuranbo = x.Dauhieuranbo,
                    Vetbamtim = x.Vetbamtim,
                    Vetthuongthanhbung = x.Vetthuongthanhbung,
                    Vtktivetthuongthanhbung = x.Vtktivetthuongthanhbung,
                    Bungmem = x.Bungmem,
                    Camungphucmac = x.Camungphucmac,
                    Vtcamungphucmac = x.Vtcamungphucmac,
                    Phan = x.Phan,
                    Tinhchatphan = x.Tinhchatphan,
                    Sothayu = x.Sothayu,
                    Vtsothayu = x.Vtsothayu,
                    Tuicungdouglas = x.Tuicungdouglas,
                    Cothathaumon = x.Cothathaumon,
                    Phanungthanhbung = x.Phanungthanhbung,
                    Cocungthanhbung = x.Cocungthanhbung,
                    Diemdau = x.Diemdau,
                    Ganto = x.Ganto,
                    Tuimatto = x.Tuimatto,
                    Dauhieumurphy = x.Dauhieumurphy,
                    Lachto = x.Lachto,
                    Khoiu = x.Khoiu,
                    Vtktkhoiu = x.Vtktkhoiu,
                    Thoaivi = x.Thoaivi,
                    Vtthoaivi = x.Vtthoaivi,
                    Tieuhoakhac = x.Tieuhoakhac,
                    Than = x.Than,
                    Thanto = x.Thanto,
                    Diemdaunieuquan = x.Diemdaunieuquan,
                    Caubangquang = x.Caubangquang,
                    Tinhhoan = x.Tinhhoan,
                    Tinhchattinhhoan = x.Tinhchattinhhoan,
                    Tuyentienliet = x.Tuyentienliet,
                    Chamthan = x.Chamthan,
                    Bapbenhthan = x.Bapbenhthan,
                    Thankinh = x.Thankinh,
                    Vetthuongvungdau = x.Vetthuongvungdau,
                    Vtktvetthuongvungdau = x.Vtktvetthuongvungdau,
                    Sungnebamtim = x.Sungnebamtim,
                    Vtktsungnebamtim = x.Vtktsungnebamtim,
                    Biendanghammat = x.Biendanghammat,
                    Vtktbiendanghammat = x.Vtktbiendanghammat,
                    Dauhieuthankinhkhutru = x.Dauhieuthankinhkhutru,
                    Motadauhieuthankinhkhutru = x.Motadauhieuthankinhkhutru,
                    Dauhieuthankinhthucvat = x.Dauhieuthankinhthucvat,
                    Motadauhieuthankinhthucvat = x.Motadauhieuthankinhthucvat,
                    Dauhieuthankinhngoaibien = x.Dauhieuthankinhngoaibien,
                    Motadauhieuthankinhngoaibien = x.Motadauhieuthankinhngoaibien,
                    Dauhieulietthankinhso = x.Dauhieulietthankinhso,
                    Motadauhieulietthankinhso = x.Motadauhieulietthankinhso,
                    Dauhieulietvandong = x.Dauhieulietvandong,
                    Motadauhieulietvandong = x.Motadauhieulietvandong,
                    Dauhieumangnao = x.Dauhieumangnao,
                    Motadauhieumangnao = x.Motadauhieumangnao,
                    Roiloancamgiac = x.Roiloancamgiac,
                    Motaroiloancamgiac = x.Motaroiloancamgiac,
                    Roiloangiacquan = x.Roiloangiacquan,
                    Motaroiloangiacquan = x.Motaroiloangiacquan,
                    Roiloanthangbang = x.Roiloanthangbang,
                    Motaroiloanthangbang = x.Motaroiloanthangbang,
                    Roiloantrinho = x.Roiloantrinho,
                    Motaroiloantrinho = x.Motaroiloantrinho,
                    Roiloanthamthan = x.Roiloantamthan,
                    Motaroiloanthamthan = x.Motaroiloanthamthan,
                    Dongkinh = x.Dongkinh,
                    Motadongkinh = x.Motadongkinh,
                    Dotquy = x.Dotquy,
                    Motadotquy = x.Motadotquy,
                    Thankinhkhac = x.Thankinhkhac,
                    Cotsong = x.Cotsong,
                    Biendangcotsong = x.Biendangcotsong,
                    Sungnebamtimcs = x.Sungnebamtimcs,
                    Diemdaucs = x.Diemdaucs,
                    Roiloancamgiacthankinhtuysong = x.Roiloancamgiacthankinhtuysong,
                    Phanxabatthuong = x.Phanxabatthuong,
                    Cacnghiemphapkham = x.Cacnghiemphapkham,
                    Cotsongkhac = x.Cotsongkhac,
                    Coxuongkhop = x.Coxuongkhop,
                    Biendangxuong = x.Biendangxuong,
                    Motabiendangxuong = x.Motabiendangxuong,
                    Vetthuong = x.Vetthuong,
                    Sungnebamtimvtt = x.Sungnebamtimvtt,
                    Motasungnebamtimvtt = x.Motasungnebamtimvtt,
                    Matlientuc = x.Matlientuc,
                    Machngoaivi = x.Machngoaivi,
                    Vandongbinhthuong = x.Vandongbinhthuong,
                    Camgiacnongsau = x.Camgiacnongsau,
                    Motacamgiacnongsau = x.Motacamgiacnongsau,
                    Chieudai = x.Chieudai,
                    Motachieudai = x.Motachieudai,
                    Biendokhop = x.Biendokhop,
                    Motabiendokhop = x.Motabiendokhop,
                    Cokhopxuongkhac = x.Cokhopxuongkhac,
                    Ranghammat = x.Ranghammat,
                    Hammat = x.Hammat,
                    Hmsungnebamtim = x.Hmsungnebamtim,
                    Hmbiendang = x.Hmbiendang,
                    Hmdiemdauchoi = x.Hmdiemdauchoi,
                    Hmmatlientuc = x.Hmmatlientuc,
                    Hmvandong = x.Hmvandong,
                    Hmhamieng = x.Hmhamieng,
                    Hmkhopcan = x.Hmkhopcan,
                    Rang = x.Rang,
                    Mat = x.Mat,
                    Tonthuong = x.Tonthuong,
                    Motatonthuong = x.Motatonthuong,
                    Supmi = x.Supmi,
                    Motasupmi = x.Motasupmi,
                    Tonthuongledao = x.Tonthuongledao,
                    Motatonthuongledao = x.Motatonthuongledao,
                    Taimuihong = x.Taimuihong,
                    Muivetthuong = x.Muivetthuong,
                    Motamuivetthuong = x.Motamuivetthuong,
                    Taivetthuong = x.Taivetthuong,
                    Motataivetthuong = x.Motataivetthuong,
                    Taichaymau = x.Taichaymau,
                    Motataichaymau = x.Motataichaymau,
                    Taimuihongkhac = x.Taimuihongkhac,
                    Benhlykhac = x.Benhlykhac,
                    Cacxetnghiem = x.Cacxetnghiem,
                    Motacacxetnghiem = x.Motacacxetnghiem,
                    Tomtatbenhan = x.Tomtatbenhan,
                    Chuandoanlucvaovienkdt = x.Chuandoanlucvaovienkdt,
                    Machuandoanlucvaovienkdt = x.Machuandoanlucvaovienkdt,
                    Chuandoanphanbiekdt = x.Chuandoanphanbiekdt,
                    Machuandoanphanbietkdt = x.Machuandoanphanbietkdt,
                    Benhchinhkdt = x.Benhchinhkdt,
                    Mabenhchinhkdt = x.Mabenhchinhkdt,
                    Benhkemtheokdt = x.Benhkemtheokdt,
                    Mabenhkemtheokdt = x.Mabenhkemtheokdt,
                    Bienchungkdt = x.Bienchungkdt,
                    Mabienchungkdt = x.Mabienchungkdt,
                    Tienluonggan = x.Tienluonggan,
                    Tienluongxa = x.Tienluongxa,
                    Huongdieutritt = x.Huongdieutritt,
                    Chedochamsoc = x.Chedochamsoc,
                    Chedodinhduong = x.Chedodinhduong,
                    Phuchoichucnang = x.Phuchoichucnang,
                    Motaphuchoichucnang = x.Motaphuchoichucnang,
                    Tuvansuckhoe = x.Tuvansuckhoe,
                    Motatuvansuckhoe = x.Motatuvansuckhoe,
                    Thoiganbacsilambenhanky = x.Thoiganbacsilambenhanky,
                    Bacsilambenhan = x.Bacsilambenhan,
                    Tomtatquatrinhbenhly = x.Tomtatquatrinhbenhly,
                    Dauhieulamsangchinh = x.Dauhieulamsangchinh,
                    Tomtatketquaxetnghiem = x.Tomtatketquaxetnghiem,
                    Noikhoa = x.Noikhoa,
                    Motanoikhoa = x.Motanoikhoa,
                    Phauthuatthuthuat = x.Phauthuatthuthuat,
                    Motaphauthuatthuthuat = x.Motaphauthuatthuthuat,
                    Tinhtrangravientk = x.Tinhtrangravientk,
                    Huongdieutri = x.Huongdieutri,
                    Thoigianbacsidieutriky = x.Thoigianbacsidieutriky,
                    Bacsidieutri = x.Bacsidieutri
                }).FirstOrDefaultAsync();
            return data;
        }
    }
}
